### ISSUE TITLE
Changes to TTGO Watch library break compilation

### ISSUE THREAD

**Issue by chiark** [stevelord/AWatch#2]
Changes to the structure of the TTGO Watch library, and notably the change to lvgl 7 from 6, has broken the project preventing compilation.  The big issue seems to be the change in approach to styles between 6 and 7.

**Comment by stevelord** [comment]
Thanks for pointing this out. I've been using an older version of the library and didn't expect this to break. Do the TTGO LVGL examples use the new v7? If so, I'll look at fixing it this weekend. If not, I might look at other options. I'm not sure fixing things here is best if they might roll back so things break again.

**Comment by chiark** [comment]
Cheers Steve, yes, the new examples do use these.  I had a quick look at the delta and it seems that there is a simple-ish cut and paste, but as this is my first attempt at getting anything to work I'd rather not break things.  The other option would be to include lvgl 6.x in the distribution.  (By the way, I also had problems with the #defines needed and #includes too - I suspect there's been more changes to the watch library)

**Comment by chiark** [comment]
I've since used the release version of the watch library and everything runs seamlessly.  It makes sense to leave things as is until the new version of the watch library is released...
